### ISSUE TITLE
플랫폼 아이콘 정렬

### ISSUE THREAD

**Issue by yj0524** [kimcore/overlayz#1]
플랫폼 아이콘이 현재는 뒤쪽에 배치되어 있습니다. (<배지><플랫폼 아이콘>)
현재 이 아이콘 위치에 대해 불편한 분들이 있으신 것 같아,
플랫폼 아이콘을 앞쪽에 배치하거나, 뒤쪽에 배치할 수 있게 설정하는 옵션을 추가해주시면 좋을 것 같습니다.

**Comment by kimcore** [comment]
9a3e28b 에서 이미 수정되었습니다!

**Comment by yj0524** [comment]
헉 바뀐 줄 몰랐네요 감사합니다
