### ISSUE TITLE
Not Found 오류 제보

### ISSUE THREAD

**Issue by AiOO** [kimcore/overlayz#2]
오버레이를 실행하면 다음 메세지가 나옵니다.

```
Not Found

해당 링크에 해당하는 오버레이를 찾을 수 없어요.
링크를 다시 한번 확인해주세요.
```

| 오버레이 설정 화면 | 오버레이 접속 화면 |
|-|-|
|  <img width="1065" alt="스크린샷 2024-01-05 오후 6 03 56" src="https://github.com/kimcore/overlayz/assets/1644576/421bd874-72b1-4131-99ca-fb847c3901df"> | <img width="1065" alt="image" src="https://github.com/kimcore/overlayz/assets/1644576/77e4476d-21f4-46c0-94d6-7d6d2184ef89"> |

이번에 치지직에서 API 업데이트(일부 URL 경로의 v1이 v2로 변경됨)가 있었는데,
그것과 연관이 있을 수도 있을 것 같습니다. 라이브러리쪽에 이슈를 올렸어야 했을 것 같기도 하네요...
제 생각에는 이 파일의 `v1`만 `v2`로 변경하면 될 것 같습니다.
https://github.com/kimcore/chzzk/blob/main/src/api/live.ts

이 커밋도 참고해보시면 좋을 것 같습니다.
https://github.com/AiOO/chazzy/commit/4d01e56dd64dcd137328339c0ebe17cbf4dbd22f

항상 감사드립니다.

**Comment by kimcore** [comment]
라이브러리와 오버레이 두쪽 모두 수정하였습니다! 제보해주셔서 감사합니다 :)
