### ISSUE TITLE
새로고침 없이 자동으로 채팅 불러오기

### ISSUE THREAD

**Issue by yj0524** [kimcore/overlayz#3]
치지직 라이브러리에서 자동으로 새로운 chatChannelId 변경을 감지하여 재연결하는 메서드가 추가되었는데,
그 메서드를 이용하여 새로고침하지 않고 채팅을 불러올 수 있으면 좋겠습니다.

**Comment by kimcore** [comment]
현재로서는 OBS가 켜지고 채팅 오버레이가 처음 불러와질 때 만약 방송 시작이 되어있지 않을 경우, 방송 시작이 될 때까지만 폴링 요청을 보내고 그 이후에는 폴링이 멈추도록 되어있습니다!
대부분의 스트리머 분들이 방송이 끝나면 OBS를 종료하시는 것으로 알고 있고, 지속적인 폴링 요청은 overlayz 서버에 무리가 갈 수 있기에 해당 기능은 추가하지 않았습니다.
