### ISSUE TITLE
nickname 오류

### ISSUE THREAD

**Issue by yj0524** [kimcore/overlayz#4]
![스크린샷 2024-04-10 174000](https://github.com/kimcore/overlayz/assets/78587308/2691a9df-4cfe-4a71-8ab5-f490b03c4b02)

![스크린샷 2024-04-10 174046](https://github.com/kimcore/overlayz/assets/78587308/940c7ccc-041e-41e7-8571-383bf60e5e70)

위 사진처럼 오류가 발생합니다. 원인은 모르겠습니다.

**Comment by yj0524** [comment]
새로고침 시 최근 채팅 불러오기 옵션이 켜져있을 때 새로고침하고 기존 채팅이 나오지 않는 것 같습니다.
새롭게 올라온 채팅은 정상적으로 표시됩니다.
![스크린샷 2024-04-10 174237](https://github.com/kimcore/overlayz/assets/78587308/fe3ead5f-89d0-4c1c-af84-3d949d9ef48b)

**Comment by kimcore** [comment]
최근 채팅에 profile 필드가 없는 채팅이 있을 경우 발생하는 오류인 듯 합니다. 
a8112df7a2bcb22daee7c762e5bb6fce62ad727b 커밋을 통해 수정될 것으로 보이나 혹시 같은 오류가 발생하는 걸 보시면 다시 제보해주시면 감사하겠습니다!
